---
version: "3.8"
services:
  movies:
    image: kavurinaveen/movies:v1
    ports:
      - 81:80
    deploy:
      replicas: 3
  train:
    image: kavurinaveen/train:v1
    ports:
      - 82:80
    deploy:
      replicas: 3
  recharge:
    image: kavurinaveen/dth:v1
    ports:
      - 83:80
    deploy:
      replicas: 3
  dth:
    image: kavurinaveen/recharge:v1
    ports:
      - 84:80
    deploy:
      replicas: 3
