version: "3.8"
services:
  movies:
    image: kavurinaveen/movies:latest
    ports:
      - 71:80
    deploy:
      replicas: 3
  train:
    image:  kavurinaveen/train:latest
    ports:
      - 72:80
    deploy:
      replicas: 3
  recharge:
    image:  kavurinaveen/dth:latest
    ports:
      - 73:80
    deploy:
      replicas: 3
  dth:
    image:  kavurinaveen/recharge:latest
    ports:
      - 74:80
    deploy:
      replicas: 3
